package wasm

import "core:mem"
import "core:fmt"
import "core:strings"

emit_js_loader :: proc(module: ^WASM_Module, wasm_filename: string, allocator: mem.Allocator) -> string {
	b := strings.builder_make(0, 2048, allocator)

	fmt.sbprint(&b, "// Auto-generated by mimir compile-wasm --js\n")
	fmt.sbprint(&b, "// ES module loader for WebAssembly module\n\n")

	fmt.sbprint(&b, "const defaultImports = {\n")

	has_env := false
	has_math := false
	has_wasi := false
	for &imp in module.imports {
		if imp.module_name == "env" { has_env = true }
		if imp.module_name == "Math" { has_math = true }
		if imp.module_name == "wasi_snapshot_preview1" { has_wasi = true }
	}

	if has_env {
		fmt.sbprint(&b, "  env: {\n")
		for &imp in module.imports {
			if imp.module_name != "env" { continue }
			if imp.field_name == "console_log_i32" {
				fmt.sbprint(&b, "    console_log_i32: (v) => console.log(v),\n")
			} else if imp.field_name == "console_log_f64" {
				fmt.sbprint(&b, "    console_log_f64: (v) => console.log(v),\n")
			} else {
				fmt.sbprintf(&b, "    %s: (...args) => {},\n", imp.field_name)
			}
		}
		fmt.sbprint(&b, "  },\n")
	}

	if has_math {
		fmt.sbprint(&b, "  Math: Math,\n")
	}

	if has_wasi {
		fmt.sbprint(&b, "  wasi_snapshot_preview1: {\n")
		fmt.sbprint(&b, "    fd_write: (fd, iovs, iovs_len, nwritten) => {\n")
		fmt.sbprint(&b, "      const mem = new Uint8Array(instance.exports.memory.buffer);\n")
		fmt.sbprint(&b, "      const view = new DataView(instance.exports.memory.buffer);\n")
		fmt.sbprint(&b, "      let written = 0;\n")
		fmt.sbprint(&b, "      for (let i = 0; i < iovs_len; i++) {\n")
		fmt.sbprint(&b, "        const ptr = view.getUint32(iovs + i * 8, true);\n")
		fmt.sbprint(&b, "        const len = view.getUint32(iovs + i * 8 + 4, true);\n")
		fmt.sbprint(&b, "        const chunk = mem.slice(ptr, ptr + len);\n")
		fmt.sbprint(&b, "        process.stdout.write(Buffer.from(chunk));\n")
		fmt.sbprint(&b, "        written += len;\n")
		fmt.sbprint(&b, "      }\n")
		fmt.sbprint(&b, "      view.setUint32(nwritten, written, true);\n")
		fmt.sbprint(&b, "      return 0;\n")
		fmt.sbprint(&b, "    },\n")
		fmt.sbprint(&b, "    proc_exit: (code) => process.exit(code),\n")
		fmt.sbprint(&b, "  },\n")
	}

	fmt.sbprint(&b, "};\n\n")

	if has_wasi {
		fmt.sbprint(&b, "let instance;\n\n")
	}

	fmt.sbprint(&b, "export async function load(importObject = {}) {\n")
	fmt.sbprint(&b, "  const mergedImports = { ...defaultImports, ...importObject };\n")
	fmt.sbprint(&b, "  let wasmModule;\n")
	fmt.sbprint(&b, "  if (typeof fetch === 'function') {\n")
	fmt.sbprintf(&b, "    const resp = await fetch(\"%s\");\n", wasm_filename)
	fmt.sbprint(&b, "    wasmModule = await WebAssembly.instantiateStreaming(resp, mergedImports);\n")
	fmt.sbprint(&b, "  } else {\n")
	fmt.sbprint(&b, "    const fs = await import('fs');\n")
	fmt.sbprintf(&b, "    const bytes = fs.readFileSync(\"%s\");\n", wasm_filename)
	fmt.sbprint(&b, "    wasmModule = await WebAssembly.instantiate(bytes, mergedImports);\n")
	fmt.sbprint(&b, "  }\n")

	if has_wasi {
		fmt.sbprint(&b, "  instance = wasmModule.instance;\n")
	}

	fmt.sbprint(&b, "  return {\n")
	fmt.sbprint(&b, "    memory: wasmModule.instance.exports.memory,\n")

	for &func in module.functions {
		if func.exported {
			fmt.sbprintf(&b, "    %s: wasmModule.instance.exports.%s,\n", func.name, func.name)
		}
	}

	fmt.sbprint(&b, "  };\n")
	fmt.sbprint(&b, "}\n")

	return strings.to_string(b)
}

emit_ts_declarations :: proc(module: ^WASM_Module, allocator: mem.Allocator) -> string {
	b := strings.builder_make(0, 1024, allocator)

	fmt.sbprint(&b, "// Auto-generated by mimir compile-wasm --js\n\n")
	fmt.sbprint(&b, "export interface WasmExports {\n")
	fmt.sbprint(&b, "  memory: WebAssembly.Memory;\n")

	for &func in module.functions {
		if !func.exported { continue }
		fmt.sbprintf(&b, "  %s: (", func.name)
		for param, idx in func.type.params {
			if idx > 0 { fmt.sbprint(&b, ", ") }
			fmt.sbprintf(&b, "p%d: %s", idx, _ts_type_str(param))
		}
		fmt.sbprint(&b, ") => ")
		if len(func.type.results) > 0 {
			fmt.sbprint(&b, _ts_type_str(func.type.results[0]))
		} else {
			fmt.sbprint(&b, "void")
		}
		fmt.sbprint(&b, ";\n")
	}

	fmt.sbprint(&b, "}\n\n")
	fmt.sbprint(&b, "export function load(importObject?: Record<string, any>): Promise<WasmExports>;\n")

	return strings.to_string(b)
}

_ts_type_str :: proc(wtype: WASM_Value_Type) -> string {
	switch wtype {
	case .I32: return "number"
	case .I64: return "bigint"
	case .F32: return "number"
	case .F64: return "number"
	case .Void: return "void"
	}
	return "number"
}
