package codegen

import "core:fmt"
import "core:mem"
import "core:os"

import parser "mimir:parser"
import binder "mimir:binder"
import checker "mimir:checker"

generate_contracts :: proc(
	module: ^parser.Module,
	bind_result: ^binder.Bind_Result,
	check_result: ^checker.Check_Result,
	output_path: string,
	allocator: mem.Allocator,
) -> Generate_Error {
	reg := &check_result.registry
	imports: Needed_Imports

	// Collect functions and classes that need contracts
	body_buf := make([dynamic]u8, 0, 1024, allocator)
	has_contracts := false

	for stmt in module.body {
		if render_contract_stmt(stmt, bind_result, check_result, reg, &body_buf, &imports, 0, allocator) {
			has_contracts = true
		}
	}

	if !has_contracts {
		return nil
	}

	// Build output
	out := make([dynamic]u8, 0, len(body_buf) + 512, allocator)
	append_str(&out, "# Auto-generated by mimir generate-contracts\n")
	append_str(&out, "import functools\n")
	append_str(&out, "from typing import get_type_hints, Union, get_args\n")
	typing_line := format_typing_imports(&imports, allocator)
	if typing_line != "" {
		append_str(&out, typing_line)
	}
	append(&out, '\n')

	// Emit the decorator (handles Union types for Python <3.10 compatibility)
	append_str(&out, "\ndef _mimir_resolve_type(tp):\n")
	append_str(&out, "    origin = getattr(tp, '__origin__', None)\n")
	append_str(&out, "    if origin is Union:\n")
	append_str(&out, "        return get_args(tp)\n")
	append_str(&out, "    if isinstance(tp, type):\n")
	append_str(&out, "        return tp\n")
	append_str(&out, "    return None\n\n")
	append_str(&out, "\ndef _mimir_check(func):\n")
	append_str(&out, "    @functools.wraps(func)\n")
	append_str(&out, "    def wrapper(*args, **kwargs):\n")
	append_str(&out, "        hints = get_type_hints(func)\n")
	append_str(&out, "        params = [k for k in hints if k != 'return']\n")
	append_str(&out, "        for i, arg in enumerate(args):\n")
	append_str(&out, "            if i < len(params):\n")
	append_str(&out, "                expected = _mimir_resolve_type(hints[params[i]])\n")
	append_str(&out, "                if expected is not None and not isinstance(arg, expected):\n")
	append_str(&out, "                    raise TypeError(\n")
	append_str(&out, "                        f\"Param '{params[i]}': expected {hints[params[i]]}, got {type(arg)}\"\n")
	append_str(&out, "                    )\n")
	append_str(&out, "        result = func(*args, **kwargs)\n")
	append_str(&out, "        if 'return' in hints:\n")
	append_str(&out, "            expected = _mimir_resolve_type(hints['return'])\n")
	append_str(&out, "            if expected is not None and not isinstance(result, expected):\n")
	append_str(&out, "                raise TypeError(\n")
	append_str(&out, "                    f\"Return: expected {hints['return']}, got {type(result)}\"\n")
	append_str(&out, "                )\n")
	append_str(&out, "        return result\n")
	append_str(&out, "    return wrapper\n\n\n")

	// Body
	for b in body_buf { append(&out, b) }

	write_err := os.write_entire_file(output_path, out[:])
	if write_err != nil {
		return Error_Data{msg = fmt.aprintf("failed to write %s", output_path, allocator = allocator)}
	}
	return nil
}

render_contract_stmt :: proc(
	stmt: parser.Stmt,
	bind_result: ^binder.Bind_Result,
	check_result: ^checker.Check_Result,
	reg: ^checker.Type_Registry,
	buf: ^[dynamic]u8,
	imports: ^Needed_Imports,
	indent: int,
	allocator: mem.Allocator,
) -> bool {
	has_any := false

	#partial switch s in stmt {
	case ^parser.Func_Def:
		// Check if function has type annotations worth enforcing
		func_type_id := find_symbol_type(s.name, s.loc, bind_result, check_result)
		if func_type_id != checker.TYPE_UNKNOWN {
			ft := checker.get_type(reg, func_type_id)
			if ct, ok := ft.info.(checker.Callable_Type); ok {
				has_typed := false
				for p in ct.params {
					if p.type_id != checker.TYPE_UNKNOWN && p.type_id != checker.TYPE_ANY {
						has_typed = true
						break
					}
				}
				if has_typed || (ct.return_type != checker.TYPE_UNKNOWN && ct.return_type != checker.TYPE_ANY) {
					append_indent(buf, indent)
					append_str(buf, "@_mimir_check\n")
					render_contract_func(s, &ct, reg, buf, imports, indent, allocator)
					has_any = true
				}
			}
		}

	case ^parser.Class_Def:
		// Emit class with decorated methods
		class_buf := make([dynamic]u8, 0, 256, allocator)
		class_has_contracts := false

		for body_stmt in s.body {
			if render_contract_stmt(body_stmt, bind_result, check_result, reg, &class_buf, imports, indent + 1, allocator) {
				class_has_contracts = true
			}
		}

		if class_has_contracts {
			append_indent(buf, indent)
			append_str(buf, "class ")
			append_str(buf, s.name)
			if len(s.bases) > 0 {
				append(buf, '(')
				for base, i in s.bases {
					if i > 0 { append_str(buf, ", ") }
					render_expr_name(base, buf)
				}
				append(buf, ')')
			}
			append_str(buf, ":\n")
			for b in class_buf { append(buf, b) }
			append(buf, '\n')
			has_any = true
		}
	}

	return has_any
}

render_contract_func :: proc(
	fd: ^parser.Func_Def,
	func_type: ^checker.Callable_Type,
	reg: ^checker.Type_Registry,
	buf: ^[dynamic]u8,
	imports: ^Needed_Imports,
	indent: int,
	allocator: mem.Allocator,
) {
	append_indent(buf, indent)
	append_str(buf, "def ")
	append_str(buf, fd.name)
	append(buf, '(')

	// Render params with annotations
	param_idx := 0
	total := 0

	for a in fd.args.args {
		if total > 0 { append_str(buf, ", ") }
		append_str(buf, a.arg)

		if a.arg != "self" && a.arg != "cls" {
			if param_idx < len(func_type.params) {
				ts := type_to_python(reg, func_type.params[param_idx].type_id, imports, allocator)
				if ts != "" {
					append_str(buf, ": ")
					append_str(buf, ts)
				}
				param_idx += 1
			} else {
				param_idx += 1
			}
		}
		total += 1
	}

	// *args
	if fd.args.vararg != nil {
		if total > 0 { append_str(buf, ", ") }
		append(buf, '*')
		append_str(buf, fd.args.vararg.arg)
		total += 1
	}

	// **kwargs
	if fd.args.kwarg != nil {
		if total > 0 { append_str(buf, ", ") }
		append_str(buf, "**")
		append_str(buf, fd.args.kwarg.arg)
	}

	append(buf, ')')

	// Return type
	ret_str := type_to_python(reg, func_type.return_type, imports, allocator)
	if ret_str != "" {
		append_str(buf, " -> ")
		append_str(buf, ret_str)
	}

	append_str(buf, ":\n")
	append_indent(buf, indent + 1)
	append_str(buf, "...\n\n")
}
