package codegen

import "core:fmt"
import "core:mem"
import "core:os"

import parser "mimir:parser"
import binder "mimir:binder"
import checker "mimir:checker"

generate_stubs :: proc(
	module: ^parser.Module,
	bind_result: ^binder.Bind_Result,
	check_result: ^checker.Check_Result,
	output_path: string,
	allocator: mem.Allocator,
) -> Generate_Error {
	reg := &check_result.registry
	imports: Needed_Imports

	// Render body to collect needed typing imports
	body_buf := make([dynamic]u8, 0, 1024, allocator)
	for stmt in module.body {
		render_stub_stmt(stmt, bind_result, check_result, reg, &body_buf, &imports, 0, allocator)
	}

	// Build final output
	out := make([dynamic]u8, 0, len(body_buf) + 256, allocator)
	append_str(&out, "# Auto-generated by mimir stubs\n")

	typing_line := format_typing_imports(&imports, allocator)
	if typing_line != "" {
		append_str(&out, typing_line)
	}
	append(&out, '\n')

	for b in body_buf { append(&out, b) }

	write_err := os.write_entire_file(output_path, out[:])
	if write_err != nil {
		return Error_Data{msg = fmt.aprintf("failed to write %s", output_path, allocator = allocator)}
	}
	return nil
}

// Look up a symbol's type by searching bind_result symbols
find_symbol_type :: proc(
	name: string,
	loc: parser.Src_Loc,
	bind_result: ^binder.Bind_Result,
	check_result: ^checker.Check_Result,
) -> checker.Type_ID {
	// Match by name + location first
	for &sym in bind_result.symbols {
		if sym.name == name && sym.def_loc.line == loc.line {
			if t, ok := check_result.symbol_types[sym.id]; ok {
				return t
			}
		}
	}
	// Fallback: match by name only
	for &sym in bind_result.symbols {
		if sym.name == name {
			if t, ok := check_result.symbol_types[sym.id]; ok {
				return t
			}
		}
	}
	return checker.TYPE_UNKNOWN
}

render_stub_stmt :: proc(
	stmt: parser.Stmt,
	bind_result: ^binder.Bind_Result,
	check_result: ^checker.Check_Result,
	reg: ^checker.Type_Registry,
	buf: ^[dynamic]u8,
	imports: ^Needed_Imports,
	indent: int,
	allocator: mem.Allocator,
) {
	#partial switch s in stmt {
	case ^parser.Func_Def:
		render_stub_func(s, false, bind_result, check_result, reg, buf, imports, indent, allocator)

	case ^parser.Async_Func_Def:
		render_stub_async_func(s, bind_result, check_result, reg, buf, imports, indent, allocator)

	case ^parser.Class_Def:
		render_stub_class(s, bind_result, check_result, reg, buf, imports, indent, allocator)

	case ^parser.Ann_Assign:
		if name, ok := s.target.(^parser.Name_Expr); ok {
			type_id := find_symbol_type(name.id, s.loc, bind_result, check_result)
			ts := type_to_python(reg, type_id, imports, allocator)
			if ts != "" {
				append_indent(buf, indent)
				append_str(buf, name.id)
				append_str(buf, ": ")
				append_str(buf, ts)
				append(buf, '\n')
			}
		}

	case ^parser.Assign:
		for target in s.targets {
			if name, ok := target.(^parser.Name_Expr); ok {
				type_id := find_symbol_type(name.id, s.loc, bind_result, check_result)
				if type_id != checker.TYPE_UNKNOWN && type_id != checker.INVALID_TYPE {
					ts := type_to_python(reg, type_id, imports, allocator)
					if ts != "" {
						append_indent(buf, indent)
						append_str(buf, name.id)
						append_str(buf, ": ")
						append_str(buf, ts)
						append(buf, '\n')
					}
				}
			}
		}

	case ^parser.Import_Stmt:
		append_indent(buf, indent)
		append_str(buf, "import ")
		for a, i in s.names {
			if i > 0 { append_str(buf, ", ") }
			append_str(buf, a.name)
			if a.asname != "" {
				append_str(buf, " as ")
				append_str(buf, a.asname)
			}
		}
		append(buf, '\n')

	case ^parser.Import_From:
		append_indent(buf, indent)
		append_str(buf, "from ")
		for _ in 0..<s.level { append(buf, '.') }
		if s.module != "" { append_str(buf, s.module) }
		append_str(buf, " import ")
		for a, i in s.names {
			if i > 0 { append_str(buf, ", ") }
			append_str(buf, a.name)
			if a.asname != "" {
				append_str(buf, " as ")
				append_str(buf, a.asname)
			}
		}
		append(buf, '\n')
	}
}

render_stub_func :: proc(
	fd: ^parser.Func_Def,
	is_method: bool,
	bind_result: ^binder.Bind_Result,
	check_result: ^checker.Check_Result,
	reg: ^checker.Type_Registry,
	buf: ^[dynamic]u8,
	imports: ^Needed_Imports,
	indent: int,
	allocator: mem.Allocator,
) {
	// Decorators
	for dec in fd.decorator_list {
		append_indent(buf, indent)
		append(buf, '@')
		render_expr_name(dec, buf)
		append(buf, '\n')
	}

	// Look up function's Callable_Type for param + return types
	func_type_id := find_symbol_type(fd.name, fd.loc, bind_result, check_result)
	func_type: ^checker.Callable_Type = nil
	if func_type_id != checker.TYPE_UNKNOWN {
		ft := checker.get_type(reg, func_type_id)
		if ct, ok := &ft.info.(checker.Callable_Type); ok {
			func_type = ct
		}
	}

	append_indent(buf, indent)
	append_str(buf, "def ")
	append_str(buf, fd.name)
	append(buf, '(')

	// Render params from AST (preserves self, *args, **kwargs structure)
	// Callable_Type excludes self, so param_idx tracks position in Callable_Type.params
	param_idx := 0
	total_written := 0

	for a in fd.args.posonlyargs {
		if total_written > 0 { append_str(buf, ", ") }
		render_stub_param(a, func_type, &param_idx, reg, buf, imports, allocator)
		total_written += 1
	}
	if len(fd.args.posonlyargs) > 0 {
		append_str(buf, ", /")
	}

	for a in fd.args.args {
		if total_written > 0 { append_str(buf, ", ") }
		render_stub_param(a, func_type, &param_idx, reg, buf, imports, allocator)
		total_written += 1
	}

	if fd.args.vararg != nil {
		if total_written > 0 { append_str(buf, ", ") }
		append(buf, '*')
		append_str(buf, fd.args.vararg.arg)
		total_written += 1
	} else if len(fd.args.kwonlyargs) > 0 {
		if total_written > 0 { append_str(buf, ", ") }
		append(buf, '*')
	}

	for a in fd.args.kwonlyargs {
		append_str(buf, ", ")
		render_stub_param(a, func_type, &param_idx, reg, buf, imports, allocator)
		total_written += 1
	}

	if fd.args.kwarg != nil {
		if total_written > 0 { append_str(buf, ", ") }
		append_str(buf, "**")
		append_str(buf, fd.args.kwarg.arg)
	}

	append(buf, ')')

	// Return type
	ret_str := ""
	if func_type != nil {
		ret_str = type_to_python(reg, func_type.return_type, imports, allocator)
	}
	if ret_str != "" {
		append_str(buf, " -> ")
		append_str(buf, ret_str)
	}

	append_str(buf, ": ...\n")
}

render_stub_param :: proc(
	arg: parser.Arg,
	func_type: ^checker.Callable_Type,
	param_idx: ^int,
	reg: ^checker.Type_Registry,
	buf: ^[dynamic]u8,
	imports: ^Needed_Imports,
	allocator: mem.Allocator,
) {
	append_str(buf, arg.arg)

	// self/cls params: no annotation in stubs
	if arg.arg == "self" || arg.arg == "cls" {
		return
	}

	// Get type from Callable_Type (which skips self)
	ts := ""
	if func_type != nil && param_idx^ < len(func_type.params) {
		ts = type_to_python(reg, func_type.params[param_idx^].type_id, imports, allocator)
		param_idx^ += 1
	} else {
		param_idx^ += 1
	}

	if ts != "" {
		append_str(buf, ": ")
		append_str(buf, ts)
	}
}

render_stub_async_func :: proc(
	fd: ^parser.Async_Func_Def,
	bind_result: ^binder.Bind_Result,
	check_result: ^checker.Check_Result,
	reg: ^checker.Type_Registry,
	buf: ^[dynamic]u8,
	imports: ^Needed_Imports,
	indent: int,
	allocator: mem.Allocator,
) {
	// Decorators
	for dec in fd.decorator_list {
		append_indent(buf, indent)
		append(buf, '@')
		render_expr_name(dec, buf)
		append(buf, '\n')
	}

	// Look up Callable_Type
	func_type_id := find_symbol_type(fd.name, fd.loc, bind_result, check_result)
	func_type: ^checker.Callable_Type = nil
	if func_type_id != checker.TYPE_UNKNOWN {
		ft := checker.get_type(reg, func_type_id)
		if ct, ok := &ft.info.(checker.Callable_Type); ok {
			func_type = ct
		}
	}

	append_indent(buf, indent)
	append_str(buf, "async def ")
	append_str(buf, fd.name)
	append(buf, '(')

	param_idx := 0
	total_written := 0
	for a in fd.args.args {
		if total_written > 0 { append_str(buf, ", ") }
		render_stub_param(a, func_type, &param_idx, reg, buf, imports, allocator)
		total_written += 1
	}
	append(buf, ')')

	if func_type != nil {
		ret_str := type_to_python(reg, func_type.return_type, imports, allocator)
		if ret_str != "" {
			append_str(buf, " -> ")
			append_str(buf, ret_str)
		}
	}

	append_str(buf, ": ...\n")
}

render_stub_class :: proc(
	cd: ^parser.Class_Def,
	bind_result: ^binder.Bind_Result,
	check_result: ^checker.Check_Result,
	reg: ^checker.Type_Registry,
	buf: ^[dynamic]u8,
	imports: ^Needed_Imports,
	indent: int,
	allocator: mem.Allocator,
) {
	// Decorators
	for dec in cd.decorator_list {
		append_indent(buf, indent)
		append(buf, '@')
		render_expr_name(dec, buf)
		append(buf, '\n')
	}

	append_indent(buf, indent)
	append_str(buf, "class ")
	append_str(buf, cd.name)

	// Bases
	if len(cd.bases) > 0 {
		append(buf, '(')
		for base, i in cd.bases {
			if i > 0 { append_str(buf, ", ") }
			render_expr_name(base, buf)
		}
		append(buf, ')')
	}
	append_str(buf, ":\n")

	// Class body
	has_content := false
	for stmt in cd.body {
		#partial switch s in stmt {
		case ^parser.Func_Def:
			render_stub_func(s, true, bind_result, check_result, reg, buf, imports, indent + 1, allocator)
			has_content = true
		case ^parser.Async_Func_Def:
			render_stub_async_func(s, bind_result, check_result, reg, buf, imports, indent + 1, allocator)
			has_content = true
		case ^parser.Ann_Assign:
			if name, ok := s.target.(^parser.Name_Expr); ok {
				type_id := find_symbol_type(name.id, s.loc, bind_result, check_result)
				ts := type_to_python(reg, type_id, imports, allocator)
				if ts != "" {
					append_indent(buf, indent + 1)
					append_str(buf, name.id)
					append_str(buf, ": ")
					append_str(buf, ts)
					append(buf, '\n')
					has_content = true
				}
			}
		case ^parser.Assign:
			for target in s.targets {
				if name, ok := target.(^parser.Name_Expr); ok {
					type_id := find_symbol_type(name.id, s.loc, bind_result, check_result)
					if type_id != checker.TYPE_UNKNOWN && type_id != checker.INVALID_TYPE {
						ts := type_to_python(reg, type_id, imports, allocator)
						if ts != "" {
							append_indent(buf, indent + 1)
							append_str(buf, name.id)
							append_str(buf, ": ")
							append_str(buf, ts)
							append(buf, '\n')
							has_content = true
						}
					}
				}
			}
		case ^parser.Class_Def:
			render_stub_class(s, bind_result, check_result, reg, buf, imports, indent + 1, allocator)
			has_content = true
		}
	}

	if !has_content {
		append_indent(buf, indent + 1)
		append_str(buf, "...\n")
	}
	append(buf, '\n')
}

// Render a simple expression (for decorators and base classes)
render_expr_name :: proc(expr: parser.Expr, buf: ^[dynamic]u8) {
	#partial switch e in expr {
	case ^parser.Name_Expr:
		append_str(buf, e.id)
	case ^parser.Attribute_Expr:
		render_expr_name(e.value, buf)
		append(buf, '.')
		append_str(buf, e.attr)
	case ^parser.Call_Expr:
		render_expr_name(e.func, buf)
		append(buf, '(')
		for arg, i in e.args {
			if i > 0 { append_str(buf, ", ") }
			render_expr_name(arg, buf)
		}
		append(buf, ')')
	case ^parser.Subscript_Expr:
		render_expr_name(e.value, buf)
		append(buf, '[')
		render_expr_name(e.slice, buf)
		append(buf, ']')
	case ^parser.Tuple_Expr:
		for elt, i in e.elts {
			if i > 0 { append_str(buf, ", ") }
			render_expr_name(elt, buf)
		}
	case ^parser.Constant_Expr:
		#partial switch v in e.value {
		case string:
			append(buf, '\'')
			append_str(buf, v)
			append(buf, '\'')
		case i64:
			s := fmt.tprintf("%d", v)
			append_str(buf, s)
		case bool:
			append_str(buf, "True" if v else "False")
		case f64:
			s := fmt.tprintf("%f", v)
			append_str(buf, s)
		}
	}
}
