package codegen

import "core:fmt"
import "core:mem"
import "core:os"

import parser "mimir:parser"
import binder "mimir:binder"
import checker "mimir:checker"

generate_tests :: proc(
	module: ^parser.Module,
	bind_result: ^binder.Bind_Result,
	check_result: ^checker.Check_Result,
	module_name: string,
	output_path: string,
	allocator: mem.Allocator,
) -> Generate_Error {
	reg := &check_result.registry

	buf := make([dynamic]u8, 0, 1024, allocator)
	append_str(&buf, "# Auto-generated by mimir generate-tests\n")
	append_str(&buf, "from hypothesis import given, strategies as st\n")
	append_str(&buf, "import ")
	append_str(&buf, module_name)
	append_str(&buf, " as m\n\n\n")

	test_count := 0

	for stmt in module.body {
		#partial switch s in stmt {
		case ^parser.Func_Def:
			if render_test_func(s, bind_result, check_result, reg, &buf, allocator) {
				test_count += 1
			}

		case ^parser.Class_Def:
			if render_test_class(s, bind_result, check_result, reg, &buf, allocator) {
				test_count += 1
			}
		}
	}

	if test_count == 0 {
		return nil
	}

	write_err := os.write_entire_file(output_path, buf[:])
	if write_err != nil {
		return Error_Data{msg = fmt.aprintf("failed to write %s", output_path, allocator = allocator)}
	}
	return nil
}

// Map a type to a hypothesis strategy expression
type_to_strategy :: proc(reg: ^checker.Type_Registry, id: checker.Type_ID, allocator: mem.Allocator) -> string {
	if id == checker.INVALID_TYPE || id == checker.TYPE_UNKNOWN || id == checker.TYPE_ANY {
		return ""
	}

	t := checker.get_type(reg, id)
	#partial switch info in t.info {
	case checker.Primitive_Type:
		switch info.kind {
		case .Int:       return "st.integers()"
		case .Float:     return "st.floats(allow_nan=False)"
		case .Str:       return "st.text()"
		case .Bytes:     return "st.binary()"
		case .Bool:      return "st.booleans()"
		case .None_Type: return "st.none()"
		case .Complex:   return ""
		case .Object:    return ""
		}
	case checker.List_Type:
		elem := type_to_strategy(reg, info.element, allocator)
		if elem == "" { return "st.lists(st.integers())" }
		return fmt.aprintf("st.lists(%s)", elem, allocator = allocator)
	case checker.Dict_Type:
		ks := type_to_strategy(reg, info.key, allocator)
		vs := type_to_strategy(reg, info.value, allocator)
		if ks == "" { ks = "st.text()" }
		if vs == "" { vs = "st.integers()" }
		return fmt.aprintf("st.dictionaries(%s, %s)", ks, vs, allocator = allocator)
	case checker.Set_Type:
		elem := type_to_strategy(reg, info.element, allocator)
		if elem == "" { return "st.frozensets(st.integers())" }
		return fmt.aprintf("st.frozensets(%s)", elem, allocator = allocator)
	case checker.Tuple_Type:
		if len(info.elements) == 0 { return "st.tuples()" }
		tbuf := make([dynamic]u8, 0, 64, allocator)
		append_str(&tbuf, "st.tuples(")
		for e, i in info.elements {
			if i > 0 { append_str(&tbuf, ", ") }
			es := type_to_strategy(reg, e, allocator)
			if es == "" { es = "st.integers()" }
			append_str(&tbuf, es)
		}
		append(&tbuf, ')')
		return string(tbuf[:])
	case checker.Union_Type:
		ubuf := make([dynamic]u8, 0, 64, allocator)
		append_str(&ubuf, "st.one_of(")
		valid := 0
		for m in info.members {
			if m == checker.TYPE_NONE {
				if valid > 0 { append_str(&ubuf, ", ") }
				append_str(&ubuf, "st.none()")
				valid += 1
				continue
			}
			ms := type_to_strategy(reg, m, allocator)
			if ms != "" {
				if valid > 0 { append_str(&ubuf, ", ") }
				append_str(&ubuf, ms)
				valid += 1
			}
		}
		append(&ubuf, ')')
		if valid == 0 { return "" }
		return string(ubuf[:])
	case checker.Literal_Int_Type:
		return "st.integers()"
	case checker.Literal_Str_Type:
		return "st.text()"
	case checker.Literal_Bool_Type:
		return "st.booleans()"
	}

	return ""
}

render_test_func :: proc(
	fd: ^parser.Func_Def,
	bind_result: ^binder.Bind_Result,
	check_result: ^checker.Check_Result,
	reg: ^checker.Type_Registry,
	buf: ^[dynamic]u8,
	allocator: mem.Allocator,
) -> bool {
	// Skip private functions
	if len(fd.name) > 0 && fd.name[0] == '_' { return false }

	// Look up Callable_Type
	func_type_id := find_symbol_type(fd.name, fd.loc, bind_result, check_result)
	if func_type_id == checker.TYPE_UNKNOWN { return false }

	ft := checker.get_type(reg, func_type_id)
	ct, ok := ft.info.(checker.Callable_Type)
	if !ok { return false }

	// Build @given(...) strategies
	strats := make([dynamic]string, 0, len(ct.params), allocator)
	param_names := make([dynamic]string, 0, len(ct.params), allocator)

	for p in ct.params {
		s := type_to_strategy(reg, p.type_id, allocator)
		if s == "" {
			return false // Can't generate strategy for a param
		}
		append(&strats, s)
		append(&param_names, p.name)
	}

	if len(strats) == 0 { return false }

	// Emit @given(...)
	append_str(buf, "@given(")
	for s, i in strats {
		if i > 0 { append_str(buf, ", ") }
		append_str(buf, param_names[i])
		append(buf, '=')
		append_str(buf, s)
	}
	append_str(buf, ")\n")

	// Emit test function
	append_str(buf, "def test_")
	append_str(buf, fd.name)
	append(buf, '(')
	for name, i in param_names {
		if i > 0 { append_str(buf, ", ") }
		append_str(buf, name)
	}
	append_str(buf, "):\n")

	// Body: call function and optionally check return type
	append_str(buf, "    result = m.")
	append_str(buf, fd.name)
	append(buf, '(')
	for name, i in param_names {
		if i > 0 { append_str(buf, ", ") }
		append_str(buf, name)
	}
	append_str(buf, ")\n")

	// Return type assertion
	ret_assert := type_to_isinstance_check(reg, ct.return_type, "result", allocator)
	if ret_assert != "" {
		append_str(buf, "    assert ")
		append_str(buf, ret_assert)
		append(buf, '\n')
	}

	append_str(buf, "\n\n")
	return true
}

render_test_class :: proc(
	cd: ^parser.Class_Def,
	bind_result: ^binder.Bind_Result,
	check_result: ^checker.Check_Result,
	reg: ^checker.Type_Registry,
	buf: ^[dynamic]u8,
	allocator: mem.Allocator,
) -> bool {
	// Skip private classes
	if len(cd.name) > 0 && cd.name[0] == '_' { return false }

	class_buf := make([dynamic]u8, 0, 256, allocator)
	method_count := 0

	for stmt in cd.body {
		#partial switch s in stmt {
		case ^parser.Func_Def:
			if len(s.name) > 0 && s.name[0] == '_' { continue }
			if render_test_method(s, cd.name, bind_result, check_result, reg, &class_buf, allocator) {
				method_count += 1
			}
		}
	}

	if method_count == 0 { return false }

	append_str(buf, "class Test")
	append_str(buf, cd.name)
	append_str(buf, ":\n")
	for b in class_buf { append(buf, b) }
	append(buf, '\n')
	return true
}

render_test_method :: proc(
	fd: ^parser.Func_Def,
	class_name: string,
	bind_result: ^binder.Bind_Result,
	check_result: ^checker.Check_Result,
	reg: ^checker.Type_Registry,
	buf: ^[dynamic]u8,
	allocator: mem.Allocator,
) -> bool {
	func_type_id := find_symbol_type(fd.name, fd.loc, bind_result, check_result)
	if func_type_id == checker.TYPE_UNKNOWN { return false }

	ft := checker.get_type(reg, func_type_id)
	ct, ok := ft.info.(checker.Callable_Type)
	if !ok { return false }

	// Build strategies (Callable_Type already excludes self)
	strats := make([dynamic]string, 0, len(ct.params), allocator)
	param_names := make([dynamic]string, 0, len(ct.params), allocator)

	for p in ct.params {
		s := type_to_strategy(reg, p.type_id, allocator)
		if s == "" {
			return false
		}
		append(&strats, s)
		append(&param_names, p.name)
	}

	// @given decorator
	if len(strats) > 0 {
		append_str(buf, "    @given(")
		for s, i in strats {
			if i > 0 { append_str(buf, ", ") }
			append_str(buf, param_names[i])
			append(buf, '=')
			append_str(buf, s)
		}
		append_str(buf, ")\n")
	}

	append_str(buf, "    def test_")
	append_str(buf, fd.name)
	append_str(buf, "(self")
	for name in param_names {
		append_str(buf, ", ")
		append_str(buf, name)
	}
	append_str(buf, "):\n")

	// Create instance and call method
	append_str(buf, "        obj = m.")
	append_str(buf, class_name)
	append_str(buf, "()\n")
	append_str(buf, "        result = obj.")
	append_str(buf, fd.name)
	append(buf, '(')
	for name, i in param_names {
		if i > 0 { append_str(buf, ", ") }
		append_str(buf, name)
	}
	append_str(buf, ")\n")

	ret_assert := type_to_isinstance_check(reg, ct.return_type, "result", allocator)
	if ret_assert != "" {
		append_str(buf, "        assert ")
		append_str(buf, ret_assert)
		append(buf, '\n')
	}

	append(buf, '\n')
	return true
}

// Generate isinstance check expression for a type
type_to_isinstance_check :: proc(reg: ^checker.Type_Registry, id: checker.Type_ID, var_name: string, allocator: mem.Allocator) -> string {
	if id == checker.INVALID_TYPE || id == checker.TYPE_UNKNOWN || id == checker.TYPE_ANY { return "" }

	t := checker.get_type(reg, id)
	#partial switch info in t.info {
	case checker.Primitive_Type:
		type_name := ""
		switch info.kind {
		case .Int:       type_name = "int"
		case .Float:     type_name = "float"
		case .Str:       type_name = "str"
		case .Bytes:     type_name = "bytes"
		case .Bool:      type_name = "bool"
		case .None_Type: return fmt.aprintf("%s is None", var_name, allocator = allocator)
		case .Complex:   type_name = "complex"
		case .Object:    return ""
		}
		if type_name != "" {
			return fmt.aprintf("isinstance(%s, %s)", var_name, type_name, allocator = allocator)
		}
	case checker.Union_Type:
		type_names := make([dynamic]string, 0, len(info.members), allocator)
		for m in info.members {
			mt := checker.get_type(reg, m)
			#partial switch mi in mt.info {
			case checker.Primitive_Type:
				#partial switch mi.kind {
				case .Int:       append(&type_names, "int")
				case .Float:     append(&type_names, "float")
				case .Str:       append(&type_names, "str")
				case .Bool:      append(&type_names, "bool")
				case .Bytes:     append(&type_names, "bytes")
				case .None_Type: append(&type_names, "type(None)")
				case:            return ""
				}
			case:
				return "" // Complex union, skip
			}
		}
		if len(type_names) == 0 { return "" }
		ubuf := make([dynamic]u8, 0, 64, allocator)
		append_str(&ubuf, "isinstance(")
		append_str(&ubuf, var_name)
		append_str(&ubuf, ", (")
		for n, i in type_names {
			if i > 0 { append_str(&ubuf, ", ") }
			append_str(&ubuf, n)
		}
		append_str(&ubuf, "))")
		return string(ubuf[:])
	case checker.Instance_Type:
		cls := checker.get_type(reg, info.class_type)
		#partial switch ci in cls.info {
		case checker.Class_Type:
			return fmt.aprintf("isinstance(%s, %s)", var_name, ci.name, allocator = allocator)
		}
	}
	return ""
}
