package platform

import "core:fmt"
import "core:mem"
import "core:os"
import "core:strings"

// Import map: structured JSON mapping package names to cache paths.
// Generated by mimir lock/install. Read by mimir run for PYTHONPATH construction
// and (future) by mimir check for third-party module resolution.

Import_Map_Entry :: struct {
	name:    string,
	version: string,
	path:    string,
	hash:    string,
}

Import_Map :: struct {
	version:  int,
	packages: [dynamic]Import_Map_Entry,
}

// Generate import map from lockfile + cache state.
generate_import_map :: proc(lf: ^Lockfile, cache: ^Cache, allocator: mem.Allocator) -> Import_Map {
	im := Import_Map{
		version  = 1,
		packages = make([dynamic]Import_Map_Entry, 0, len(lf.packages), allocator),
	}

	for pkg in lf.packages {
		path := ""

		// Try CAS path first
		if len(pkg.hash) > 0 {
			cas_path := cas_dir(cache, pkg.hash)
			if os.is_directory(cas_path) {
				path = cas_path
			}
		}

		// Fall back to legacy versioned dir
		if path == "" {
			legacy_path, found := find_package_version(cache, pkg.name, pkg.version)
			if found {
				path = legacy_path
			}
		}

		if path != "" {
			append(&im.packages, Import_Map_Entry{
				name    = pkg.name,
				version = pkg.version,
				path    = path,
				hash    = pkg.hash,
			})
		}
	}

	return im
}

// Write import map as JSON to .mimir/import_map.json in the project directory.
write_import_map :: proc(im: ^Import_Map, project_dir: string, allocator: mem.Allocator) -> Platform_Error {
	mimir_dir := strings.concatenate({project_dir, "/.mimir"}, allocator)
	mkdir_err := os.make_directory_all(mimir_dir)
	if mkdir_err != nil && mkdir_err != .Exist {
		return Platform_Error_Data{msg = fmt.tprintf("cannot create .mimir directory: %v", mkdir_err)}
	}

	path := strings.concatenate({mimir_dir, "/import_map.json"}, allocator)

	// Build JSON manually (simple, no external dependency)
	buf := make([dynamic]u8, 0, 512, allocator)
	append_str(&buf, "{\n")
	append_str(&buf, fmt.tprintf("  \"version\": %d,\n", im.version))
	append_str(&buf, "  \"packages\": {\n")

	for entry, i in im.packages {
		append_str(&buf, fmt.tprintf("    \"%s\": {\n", json_escape(entry.name)))
		append_str(&buf, fmt.tprintf("      \"version\": \"%s\",\n", json_escape(entry.version)))
		append_str(&buf, fmt.tprintf("      \"path\": \"%s\",\n", json_escape(entry.path)))
		append_str(&buf, fmt.tprintf("      \"hash\": \"%s\"\n", json_escape(entry.hash)))
		if i < len(im.packages) - 1 {
			append_str(&buf, "    },\n")
		} else {
			append_str(&buf, "    }\n")
		}
	}

	append_str(&buf, "  }\n")
	append_str(&buf, "}\n")

	write_err := os.write_entire_file(path, buf[:])
	if write_err != nil {
		return Platform_Error_Data{msg = fmt.tprintf("cannot write import map: %v", write_err)}
	}

	return nil
}

// Read import map from .mimir/import_map.json. Returns package paths for PYTHONPATH.
read_import_map_paths :: proc(project_dir: string, allocator: mem.Allocator) -> (paths: [dynamic]string, ok: bool) {
	path := strings.concatenate({project_dir, "/.mimir/import_map.json"}, allocator)
	if !os.is_file(path) {
		return {}, false
	}

	data, read_err := os.read_entire_file(path, allocator)
	if read_err != nil {
		return {}, false
	}

	// Simple JSON path extraction — find "path": "..." entries
	result := make([dynamic]string, 0, 16, allocator)
	content := string(data)

	idx := 0
	for idx < len(content) {
		// Find "path": "
		path_key := "\"path\": \""
		pos := strings.index(content[idx:], path_key)
		if pos < 0 { break }
		start := idx + pos + len(path_key)
		// Find closing quote
		end := strings.index_byte(content[start:], '"')
		if end < 0 { break }
		pkg_path := content[start:start + end]
		if len(pkg_path) > 0 && os.is_directory(pkg_path) {
			append(&result, strings.clone(pkg_path, allocator))
		}
		idx = start + end + 1
	}

	return result, len(result) > 0
}

// ==================== Helpers ====================

@(private = "file")
append_str :: proc(buf: ^[dynamic]u8, s: string) {
	for c in transmute([]u8)s {
		append(buf, c)
	}
}

@(private = "file")
json_escape :: proc(s: string) -> string {
	// Simple escape for JSON strings — handles \, ", newlines
	needs_escape := false
	for c in s {
		if c == '"' || c == '\\' || c == '\n' || c == '\r' || c == '\t' {
			needs_escape = true
			break
		}
	}
	if !needs_escape { return s }

	buf := make([dynamic]u8, 0, len(s) + 8)
	for c in s {
		switch c {
		case '"':  append(&buf, '\\'); append(&buf, '"')
		case '\\': append(&buf, '\\'); append(&buf, '\\')
		case '\n': append(&buf, '\\'); append(&buf, 'n')
		case '\r': append(&buf, '\\'); append(&buf, 'r')
		case '\t': append(&buf, '\\'); append(&buf, 't')
		case:      append(&buf, u8(c))
		}
	}
	return string(buf[:])
}
