package platform

import "core:fmt"
import "core:mem"
import "core:os"
import "core:slice"
import "core:strings"

// Lockfile manager for mimir.lock.
// All packages (direct + transitive) with exact pinned versions.

Locked_Package :: struct {
	name:    string,
	version: string,
	hash:    string, // CAS hash (FNV-64a of "name==version")
}

Lockfile :: struct {
	packages: [dynamic]Locked_Package,
}

// Read mimir.lock from a path.
read_lockfile :: proc(path: string, allocator: mem.Allocator) -> (Lockfile, Platform_Error) {
	data, read_err := os.read_entire_file(path, allocator)
	if read_err != nil {
		return {}, Platform_Error_Data{msg = fmt.tprintf("cannot read '%s': %v", path, read_err)}
	}

	doc, parse_err := toml_parse(string(data), allocator)
	if parse_err != nil {
		return {}, parse_err
	}

	lf := Lockfile{
		packages = make([dynamic]Locked_Package, 0, 16, allocator),
	}

	// Read [packages] section
	if pkg_table, has_pkgs := doc.tables["packages"]; has_pkgs {
		for name in pkg_table.order {
			version := ""
			if val, val_ok := pkg_table.entries[name]; val_ok {
				if s, is_str := val.(string); is_str {
					version = s
				}
			}
			append(&lf.packages, Locked_Package{
				name    = name,
				version = version,
			})
		}
	}

	// Read [hashes] section (Layer 4)
	if hash_table, has_hashes := doc.tables["hashes"]; has_hashes {
		for &pkg in lf.packages {
			if val, val_ok := hash_table.entries[pkg.name]; val_ok {
				if s, is_str := val.(string); is_str {
					pkg.hash = s
				}
			}
		}
	}

	return lf, nil
}

// Write lockfile sorted by package name for determinism.
write_lockfile :: proc(lf: ^Lockfile, path: string, allocator: mem.Allocator) -> Platform_Error {
	// Sort packages by name
	slice.sort_by(lf.packages[:], proc(a, b: Locked_Package) -> bool {
		return a.name < b.name
	})

	doc := Toml_Document{
		tables      = make(map[string]Toml_Table, 2, allocator),
		table_order = make([dynamic]string, 0, 2, allocator),
		root = Toml_Table{
			entries = make(map[string]Toml_Value, 2, allocator),
			order   = make([dynamic]string, 0, 2, allocator),
		},
	}

	// Build [packages] section
	for pkg in lf.packages {
		toml_set(&doc, "packages", pkg.name, pkg.version, allocator)
	}

	// Build [hashes] section (Layer 4 — CAS integrity)
	has_hashes := false
	for pkg in lf.packages {
		if len(pkg.hash) > 0 {
			has_hashes = true
			break
		}
	}
	if has_hashes {
		for pkg in lf.packages {
			if len(pkg.hash) > 0 {
				toml_set(&doc, "hashes", pkg.name, pkg.hash, allocator)
			}
		}
	}

	// Serialize with header comment
	content_body := toml_write(&doc, allocator)
	header := "# Auto-generated by mimir lock. Do not edit.\n\n"
	content := strings.concatenate({header, content_body}, allocator)

	write_err := os.write_entire_file(path, transmute([]u8)content)
	if write_err != nil {
		return Platform_Error_Data{msg = fmt.tprintf("cannot write '%s': %v", path, write_err)}
	}

	return nil
}

// Given a mimir.toml path, return sibling mimir.lock path.
lockfile_path :: proc(config_path: string, allocator: mem.Allocator) -> string {
	dir := parent_dir(config_path)
	return strings.concatenate({dir, "/mimir.lock"}, allocator)
}
