package platform

import "core:fmt"
import "core:mem"
import "core:os"

// Runtime shim generators for mimir.* virtual modules.
// Each generates Python code that provides real implementations matching type stubs.
// Used by `mimir run` to inject virtual modules into sys.modules before running user scripts.

// ==================== Bootstrap ====================

// Generate a complete bootstrap script that injects all virtual modules and runs the user's script.
generate_run_bootstrap :: proc(script: string, script_args: []string, allocator: mem.Allocator) -> string {
	buf := make([dynamic]u8, 0, 16384, allocator)

	// Header
	_rs_sb(&buf, "#!/usr/bin/env python3\n")
	_rs_sb(&buf, "'''mimir run bootstrap - generated by mimir'''\n")
	_rs_sb(&buf, "import sys, os, importlib.util\n")
	_rs_sb(&buf, "from types import ModuleType\n")
	_rs_sb(&buf, "\n")

	// Parent module
	_rs_sb(&buf, "# Inject mimir parent module\n")
	_rs_sb(&buf, "if 'mimir' not in sys.modules:\n")
	_rs_sb(&buf, "    _mimir = ModuleType('mimir')\n")
	_rs_sb(&buf, "    _mimir.__path__ = []\n")
	_rs_sb(&buf, "    sys.modules['mimir'] = _mimir\n")
	_rs_sb(&buf, "\n")

	// Set sys.argv to match direct execution
	_rs_sb(&buf, fmt.tprintf("sys.argv = ['%s'", _rs_escape_py_str(script)))
	for arg in script_args {
		_rs_sb(&buf, fmt.tprintf(", '%s'", _rs_escape_py_str(arg)))
	}
	_rs_sb(&buf, "]\n")
	_rs_sb(&buf, "\n")

	// Inject all virtual module shims
	_rs_sb(&buf, generate_db_shim(allocator))
	_rs_sb(&buf, generate_crypt_shim(allocator))
	_rs_sb(&buf, generate_json_shim(allocator))

	// Run user script via importlib
	_rs_sb(&buf, "# Run user script\n")
	_rs_sb(&buf, fmt.tprintf("_script_dir = '%s'\n", _rs_escape_py_str(parent_dir(script))))
	_rs_sb(&buf, "if _script_dir not in sys.path:\n")
	_rs_sb(&buf, "    sys.path.insert(0, _script_dir)\n")
	_rs_sb(&buf, "\n")
	_rs_sb(&buf, fmt.tprintf("_script_path = '%s'\n", _rs_escape_py_str(script)))
	_rs_sb(&buf, "spec = importlib.util.spec_from_file_location('__main__', _script_path)\n")
	_rs_sb(&buf, "if spec is None or spec.loader is None:\n")
	_rs_sb(&buf, "    print(f'mimir run: failed to load {_script_path}', file=sys.stderr)\n")
	_rs_sb(&buf, "    sys.exit(1)\n")
	_rs_sb(&buf, "mod = importlib.util.module_from_spec(spec)\n")
	_rs_sb(&buf, "sys.modules['__main__'] = mod\n")
	_rs_sb(&buf, "spec.loader.exec_module(mod)\n")

	return string(buf[:])
}

// Write bootstrap content to a temp file. Returns path and success.
write_run_bootstrap :: proc(content: string, allocator: mem.Allocator) -> (path: string, ok: bool) {
	tmp_dir, tmp_err := os.temp_directory(allocator)
	if tmp_err != nil {
		tmp_dir = "/tmp"
	}

	pid := os.get_pid()
	boot_path := fmt.aprintf("%s/_mimir_run_%d.py", tmp_dir, pid, allocator = allocator)

	write_err := os.write_entire_file(boot_path, transmute([]u8)content)
	if write_err != nil {
		fmt.eprintfln("mimir run: failed to write bootstrap to %s: %v", boot_path, write_err)
		return "", false
	}

	return boot_path, true
}

// ==================== mimir.db shim ====================

generate_db_shim :: proc(allocator: mem.Allocator) -> string {
	buf := make([dynamic]u8, 0, 4096, allocator)

	_rs_sb(&buf, "# ---- mimir.db runtime shim ----\n")
	_rs_sb(&buf, "import sqlite3\n")
	_rs_sb(&buf, "from urllib.parse import urlparse\n")
	_rs_sb(&buf, "\n")

	// Connection class
	_rs_sb(&buf, "class _DB_Connection:\n")
	_rs_sb(&buf, "    def __init__(self, raw_conn, scheme):\n")
	_rs_sb(&buf, "        self._conn = raw_conn\n")
	_rs_sb(&buf, "        self._scheme = scheme\n")
	_rs_sb(&buf, "        self._in_tx = False\n")
	_rs_sb(&buf, "\n")
	_rs_sb(&buf, "    def query(self, sql, params=None, result=None):\n")
	_rs_sb(&buf, "        cur = self._conn.cursor()\n")
	_rs_sb(&buf, "        cur.execute(sql, params or ())\n")
	_rs_sb(&buf, "        cols = [d[0] for d in cur.description] if cur.description else []\n")
	_rs_sb(&buf, "        rows = [dict(zip(cols, row)) for row in cur.fetchall()]\n")
	_rs_sb(&buf, "        if result is not None:\n")
	_rs_sb(&buf, "            rows = [result(**r) for r in rows]\n")
	_rs_sb(&buf, "        return rows\n")
	_rs_sb(&buf, "\n")
	_rs_sb(&buf, "    def execute(self, sql, params=None):\n")
	_rs_sb(&buf, "        cur = self._conn.cursor()\n")
	_rs_sb(&buf, "        cur.execute(sql, params or ())\n")
	_rs_sb(&buf, "        if not self._in_tx:\n")
	_rs_sb(&buf, "            self._conn.commit()\n")
	_rs_sb(&buf, "        return cur.rowcount\n")
	_rs_sb(&buf, "\n")
	_rs_sb(&buf, "    def close(self):\n")
	_rs_sb(&buf, "        self._conn.close()\n")
	_rs_sb(&buf, "\n")
	_rs_sb(&buf, "    @property\n")
	_rs_sb(&buf, "    def in_transaction(self):\n")
	_rs_sb(&buf, "        return self._in_tx\n")
	_rs_sb(&buf, "\n")

	// Transaction class
	_rs_sb(&buf, "class _DB_Transaction:\n")
	_rs_sb(&buf, "    def __init__(self, conn):\n")
	_rs_sb(&buf, "        self._conn = conn\n")
	_rs_sb(&buf, "        self._conn._in_tx = True\n")
	_rs_sb(&buf, "        if self._conn._scheme == 'sqlite':\n")
	_rs_sb(&buf, "            self._conn._conn.execute('BEGIN')\n")
	_rs_sb(&buf, "        else:\n")
	_rs_sb(&buf, "            self._conn._conn.autocommit = False\n")
	_rs_sb(&buf, "\n")
	_rs_sb(&buf, "    def commit(self):\n")
	_rs_sb(&buf, "        self._conn._conn.commit()\n")
	_rs_sb(&buf, "        self._conn._in_tx = False\n")
	_rs_sb(&buf, "        if self._conn._scheme != 'sqlite':\n")
	_rs_sb(&buf, "            self._conn._conn.autocommit = True\n")
	_rs_sb(&buf, "\n")
	_rs_sb(&buf, "    def rollback(self):\n")
	_rs_sb(&buf, "        self._conn._conn.rollback()\n")
	_rs_sb(&buf, "        self._conn._in_tx = False\n")
	_rs_sb(&buf, "        if self._conn._scheme != 'sqlite':\n")
	_rs_sb(&buf, "            self._conn._conn.autocommit = True\n")
	_rs_sb(&buf, "\n")
	_rs_sb(&buf, "    def __enter__(self):\n")
	_rs_sb(&buf, "        return self\n")
	_rs_sb(&buf, "\n")
	_rs_sb(&buf, "    def __exit__(self, exc_type, exc_val, exc_tb):\n")
	_rs_sb(&buf, "        if exc_type is not None:\n")
	_rs_sb(&buf, "            self.rollback()\n")
	_rs_sb(&buf, "        else:\n")
	_rs_sb(&buf, "            self.commit()\n")
	_rs_sb(&buf, "        return False\n")
	_rs_sb(&buf, "\n")

	// connect function
	_rs_sb(&buf, "def _db_connect(url):\n")
	_rs_sb(&buf, "    parsed = urlparse(url)\n")
	_rs_sb(&buf, "    scheme = parsed.scheme.lower()\n")
	_rs_sb(&buf, "    if scheme == 'sqlite':\n")
	_rs_sb(&buf, "        db_path = parsed.path\n")
	_rs_sb(&buf, "        if db_path.startswith('/'):\n")
	_rs_sb(&buf, "            db_path = db_path[1:]\n")
	_rs_sb(&buf, "        if not db_path or db_path == ':memory:':\n")
	_rs_sb(&buf, "            db_path = ':memory:'\n")
	_rs_sb(&buf, "        conn = sqlite3.connect(db_path)\n")
	_rs_sb(&buf, "        conn.isolation_level = None  # autocommit by default\n")
	_rs_sb(&buf, "        return _DB_Connection(conn, 'sqlite')\n")
	_rs_sb(&buf, "    elif scheme in ('postgresql', 'postgres'):\n")
	_rs_sb(&buf, "        try:\n")
	_rs_sb(&buf, "            import psycopg2\n")
	_rs_sb(&buf, "        except ImportError:\n")
	_rs_sb(&buf, "            raise ImportError(\n")
	_rs_sb(&buf, "                'mimir.db: PostgreSQL requires psycopg2. '\n")
	_rs_sb(&buf, "                'Install: pip install psycopg2-binary'\n")
	_rs_sb(&buf, "            )\n")
	_rs_sb(&buf, "        conn = psycopg2.connect(url)\n")
	_rs_sb(&buf, "        conn.autocommit = True\n")
	_rs_sb(&buf, "        return _DB_Connection(conn, 'postgresql')\n")
	_rs_sb(&buf, "    elif scheme == 'mysql':\n")
	_rs_sb(&buf, "        try:\n")
	_rs_sb(&buf, "            import mysql.connector\n")
	_rs_sb(&buf, "        except ImportError:\n")
	_rs_sb(&buf, "            raise ImportError(\n")
	_rs_sb(&buf, "                'mimir.db: MySQL requires mysql-connector-python. '\n")
	_rs_sb(&buf, "                'Install: pip install mysql-connector-python'\n")
	_rs_sb(&buf, "            )\n")
	_rs_sb(&buf, "        conn = mysql.connector.connect(\n")
	_rs_sb(&buf, "            host=parsed.hostname or 'localhost',\n")
	_rs_sb(&buf, "            port=parsed.port or 3306,\n")
	_rs_sb(&buf, "            user=parsed.username or '',\n")
	_rs_sb(&buf, "            password=parsed.password or '',\n")
	_rs_sb(&buf, "            database=parsed.path.lstrip('/'),\n")
	_rs_sb(&buf, "            autocommit=True,\n")
	_rs_sb(&buf, "        )\n")
	_rs_sb(&buf, "        return _DB_Connection(conn, 'mysql')\n")
	_rs_sb(&buf, "    else:\n")
	_rs_sb(&buf, "        raise ValueError(f'mimir.db: unsupported database scheme: {scheme}')\n")
	_rs_sb(&buf, "\n")

	// Free functions
	_rs_sb(&buf, "def _db_query(conn, sql, params=None, result=None):\n")
	_rs_sb(&buf, "    return conn.query(sql, params, result)\n")
	_rs_sb(&buf, "\n")
	_rs_sb(&buf, "def _db_execute(conn, sql, params=None):\n")
	_rs_sb(&buf, "    return conn.execute(sql, params)\n")
	_rs_sb(&buf, "\n")
	_rs_sb(&buf, "def _db_transaction(conn):\n")
	_rs_sb(&buf, "    return _DB_Transaction(conn)\n")
	_rs_sb(&buf, "\n")

	// Module wiring
	_rs_sb(&buf, "# Wire mimir.db module\n")
	_rs_sb(&buf, "_db_mod = ModuleType('mimir.db')\n")
	_rs_sb(&buf, "_db_mod.Connection = _DB_Connection\n")
	_rs_sb(&buf, "_db_mod.Transaction = _DB_Transaction\n")
	_rs_sb(&buf, "_db_mod.connect = _db_connect\n")
	_rs_sb(&buf, "_db_mod.query = _db_query\n")
	_rs_sb(&buf, "_db_mod.execute = _db_execute\n")
	_rs_sb(&buf, "_db_mod.transaction = _db_transaction\n")
	_rs_sb(&buf, "sys.modules['mimir.db'] = _db_mod\n")
	_rs_sb(&buf, "\n")

	return string(buf[:])
}

// ==================== mimir.crypt shim ====================

generate_crypt_shim :: proc(allocator: mem.Allocator) -> string {
	buf := make([dynamic]u8, 0, 4096, allocator)

	_rs_sb(&buf, "# ---- mimir.crypt runtime shim ----\n")
	_rs_sb(&buf, "import hashlib, hmac, secrets\n")
	_rs_sb(&buf, "\n")

	// Hash namespace
	_rs_sb(&buf, "class _HashNS:\n")
	_rs_sb(&buf, "    def sha256(self, data): return hashlib.sha256(data).hexdigest()\n")
	_rs_sb(&buf, "    def sha512(self, data): return hashlib.sha512(data).hexdigest()\n")
	_rs_sb(&buf, "    def sha3_256(self, data): return hashlib.sha3_256(data).hexdigest()\n")
	_rs_sb(&buf, "    def sha1(self, data): return hashlib.sha1(data).hexdigest()\n")
	_rs_sb(&buf, "    def md5(self, data): return hashlib.md5(data).hexdigest()\n")
	_rs_sb(&buf, "    def bcrypt(self, password):\n")
	_rs_sb(&buf, "        try:\n")
	_rs_sb(&buf, "            import bcrypt as _bcrypt\n")
	_rs_sb(&buf, "        except ImportError:\n")
	_rs_sb(&buf, "            raise ImportError(\n")
	_rs_sb(&buf, "                'mimir.crypt: bcrypt requires the bcrypt package. '\n")
	_rs_sb(&buf, "                'Install: pip install bcrypt'\n")
	_rs_sb(&buf, "            )\n")
	_rs_sb(&buf, "        pwd = password.encode('utf-8') if isinstance(password, str) else password\n")
	_rs_sb(&buf, "        return _bcrypt.hashpw(pwd, _bcrypt.gensalt()).decode('utf-8')\n")
	_rs_sb(&buf, "    def argon2(self, password):\n")
	_rs_sb(&buf, "        try:\n")
	_rs_sb(&buf, "            from argon2 import PasswordHasher\n")
	_rs_sb(&buf, "        except ImportError:\n")
	_rs_sb(&buf, "            raise ImportError(\n")
	_rs_sb(&buf, "                'mimir.crypt: argon2 requires the argon2-cffi package. '\n")
	_rs_sb(&buf, "                'Install: pip install argon2-cffi'\n")
	_rs_sb(&buf, "            )\n")
	_rs_sb(&buf, "        return PasswordHasher().hash(password)\n")
	_rs_sb(&buf, "\n")

	// Verify namespace
	_rs_sb(&buf, "class _VerifyNS:\n")
	_rs_sb(&buf, "    def bcrypt(self, password, hashed):\n")
	_rs_sb(&buf, "        try:\n")
	_rs_sb(&buf, "            import bcrypt as _bcrypt\n")
	_rs_sb(&buf, "        except ImportError:\n")
	_rs_sb(&buf, "            raise ImportError(\n")
	_rs_sb(&buf, "                'mimir.crypt: bcrypt requires the bcrypt package. '\n")
	_rs_sb(&buf, "                'Install: pip install bcrypt'\n")
	_rs_sb(&buf, "            )\n")
	_rs_sb(&buf, "        pwd = password.encode('utf-8') if isinstance(password, str) else password\n")
	_rs_sb(&buf, "        h = hashed.encode('utf-8') if isinstance(hashed, str) else hashed\n")
	_rs_sb(&buf, "        return _bcrypt.checkpw(pwd, h)\n")
	_rs_sb(&buf, "    def argon2(self, password, hashed):\n")
	_rs_sb(&buf, "        try:\n")
	_rs_sb(&buf, "            from argon2 import PasswordHasher\n")
	_rs_sb(&buf, "        except ImportError:\n")
	_rs_sb(&buf, "            raise ImportError(\n")
	_rs_sb(&buf, "                'mimir.crypt: argon2 requires the argon2-cffi package. '\n")
	_rs_sb(&buf, "                'Install: pip install argon2-cffi'\n")
	_rs_sb(&buf, "            )\n")
	_rs_sb(&buf, "        try:\n")
	_rs_sb(&buf, "            return PasswordHasher().verify(hashed, password)\n")
	_rs_sb(&buf, "        except Exception:\n")
	_rs_sb(&buf, "            return False\n")
	_rs_sb(&buf, "\n")

	// Encrypt namespace
	_rs_sb(&buf, "class _EncryptNS:\n")
	_rs_sb(&buf, "    def _get_crypto(self):\n")
	_rs_sb(&buf, "        try:\n")
	_rs_sb(&buf, "            from cryptography.hazmat.primitives.ciphers.aead import AESGCM, ChaCha20Poly1305\n")
	_rs_sb(&buf, "            from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes\n")
	_rs_sb(&buf, "            from cryptography.hazmat.primitives import padding\n")
	_rs_sb(&buf, "            return {'AESGCM': AESGCM, 'ChaCha20Poly1305': ChaCha20Poly1305,\n")
	_rs_sb(&buf, "                    'Cipher': Cipher, 'algorithms': algorithms, 'modes': modes,\n")
	_rs_sb(&buf, "                    'padding': padding}\n")
	_rs_sb(&buf, "        except ImportError:\n")
	_rs_sb(&buf, "            raise ImportError(\n")
	_rs_sb(&buf, "                'mimir.crypt: encryption requires the cryptography package. '\n")
	_rs_sb(&buf, "                'Install: pip install cryptography'\n")
	_rs_sb(&buf, "            )\n")
	_rs_sb(&buf, "    def aes_gcm(self, key, plaintext):\n")
	_rs_sb(&buf, "        c = self._get_crypto()\n")
	_rs_sb(&buf, "        nonce = secrets.token_bytes(12)\n")
	_rs_sb(&buf, "        ct = c['AESGCM'](key).encrypt(nonce, plaintext, None)\n")
	_rs_sb(&buf, "        return nonce + ct\n")
	_rs_sb(&buf, "    def aes_cbc(self, key, plaintext):\n")
	_rs_sb(&buf, "        c = self._get_crypto()\n")
	_rs_sb(&buf, "        iv = secrets.token_bytes(16)\n")
	_rs_sb(&buf, "        padder = c['padding'].PKCS7(128).padder()\n")
	_rs_sb(&buf, "        padded = padder.update(plaintext) + padder.finalize()\n")
	_rs_sb(&buf, "        cipher = c['Cipher'](c['algorithms'].AES(key), c['modes'].CBC(iv))\n")
	_rs_sb(&buf, "        enc = cipher.encryptor()\n")
	_rs_sb(&buf, "        return iv + enc.update(padded) + enc.finalize()\n")
	_rs_sb(&buf, "    def aes_ctr(self, key, plaintext):\n")
	_rs_sb(&buf, "        c = self._get_crypto()\n")
	_rs_sb(&buf, "        nonce = secrets.token_bytes(16)\n")
	_rs_sb(&buf, "        cipher = c['Cipher'](c['algorithms'].AES(key), c['modes'].CTR(nonce))\n")
	_rs_sb(&buf, "        enc = cipher.encryptor()\n")
	_rs_sb(&buf, "        return nonce + enc.update(plaintext) + enc.finalize()\n")
	_rs_sb(&buf, "    def aes_ecb(self, key, plaintext):\n")
	_rs_sb(&buf, "        c = self._get_crypto()\n")
	_rs_sb(&buf, "        padder = c['padding'].PKCS7(128).padder()\n")
	_rs_sb(&buf, "        padded = padder.update(plaintext) + padder.finalize()\n")
	_rs_sb(&buf, "        cipher = c['Cipher'](c['algorithms'].AES(key), c['modes'].ECB())\n")
	_rs_sb(&buf, "        enc = cipher.encryptor()\n")
	_rs_sb(&buf, "        return enc.update(padded) + enc.finalize()\n")
	_rs_sb(&buf, "    def chacha20(self, key, plaintext):\n")
	_rs_sb(&buf, "        c = self._get_crypto()\n")
	_rs_sb(&buf, "        nonce = secrets.token_bytes(12)\n")
	_rs_sb(&buf, "        ct = c['ChaCha20Poly1305'](key).encrypt(nonce, plaintext, None)\n")
	_rs_sb(&buf, "        return nonce + ct\n")
	_rs_sb(&buf, "\n")

	// Decrypt namespace
	_rs_sb(&buf, "class _DecryptNS:\n")
	_rs_sb(&buf, "    def _get_crypto(self):\n")
	_rs_sb(&buf, "        try:\n")
	_rs_sb(&buf, "            from cryptography.hazmat.primitives.ciphers.aead import AESGCM, ChaCha20Poly1305\n")
	_rs_sb(&buf, "            from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes\n")
	_rs_sb(&buf, "            from cryptography.hazmat.primitives import padding\n")
	_rs_sb(&buf, "            return {'AESGCM': AESGCM, 'ChaCha20Poly1305': ChaCha20Poly1305,\n")
	_rs_sb(&buf, "                    'Cipher': Cipher, 'algorithms': algorithms, 'modes': modes,\n")
	_rs_sb(&buf, "                    'padding': padding}\n")
	_rs_sb(&buf, "        except ImportError:\n")
	_rs_sb(&buf, "            raise ImportError(\n")
	_rs_sb(&buf, "                'mimir.crypt: decryption requires the cryptography package. '\n")
	_rs_sb(&buf, "                'Install: pip install cryptography'\n")
	_rs_sb(&buf, "            )\n")
	_rs_sb(&buf, "    def aes_gcm(self, key, ciphertext):\n")
	_rs_sb(&buf, "        c = self._get_crypto()\n")
	_rs_sb(&buf, "        nonce, ct = ciphertext[:12], ciphertext[12:]\n")
	_rs_sb(&buf, "        return c['AESGCM'](key).decrypt(nonce, ct, None)\n")
	_rs_sb(&buf, "    def aes_cbc(self, key, ciphertext):\n")
	_rs_sb(&buf, "        c = self._get_crypto()\n")
	_rs_sb(&buf, "        iv, ct = ciphertext[:16], ciphertext[16:]\n")
	_rs_sb(&buf, "        cipher = c['Cipher'](c['algorithms'].AES(key), c['modes'].CBC(iv))\n")
	_rs_sb(&buf, "        dec = cipher.decryptor()\n")
	_rs_sb(&buf, "        padded = dec.update(ct) + dec.finalize()\n")
	_rs_sb(&buf, "        unpadder = c['padding'].PKCS7(128).unpadder()\n")
	_rs_sb(&buf, "        return unpadder.update(padded) + unpadder.finalize()\n")
	_rs_sb(&buf, "    def aes_ctr(self, key, ciphertext):\n")
	_rs_sb(&buf, "        c = self._get_crypto()\n")
	_rs_sb(&buf, "        nonce, ct = ciphertext[:16], ciphertext[16:]\n")
	_rs_sb(&buf, "        cipher = c['Cipher'](c['algorithms'].AES(key), c['modes'].CTR(nonce))\n")
	_rs_sb(&buf, "        dec = cipher.decryptor()\n")
	_rs_sb(&buf, "        return dec.update(ct) + dec.finalize()\n")
	_rs_sb(&buf, "    def aes_ecb(self, key, ciphertext):\n")
	_rs_sb(&buf, "        c = self._get_crypto()\n")
	_rs_sb(&buf, "        cipher = c['Cipher'](c['algorithms'].AES(key), c['modes'].ECB())\n")
	_rs_sb(&buf, "        dec = cipher.decryptor()\n")
	_rs_sb(&buf, "        padded = dec.update(ciphertext) + dec.finalize()\n")
	_rs_sb(&buf, "        unpadder = c['padding'].PKCS7(128).unpadder()\n")
	_rs_sb(&buf, "        return unpadder.update(padded) + unpadder.finalize()\n")
	_rs_sb(&buf, "    def chacha20(self, key, ciphertext):\n")
	_rs_sb(&buf, "        c = self._get_crypto()\n")
	_rs_sb(&buf, "        nonce, ct = ciphertext[:12], ciphertext[12:]\n")
	_rs_sb(&buf, "        return c['ChaCha20Poly1305'](key).decrypt(nonce, ct, None)\n")
	_rs_sb(&buf, "\n")

	// Token namespace
	_rs_sb(&buf, "class _TokenNS:\n")
	_rs_sb(&buf, "    def bytes(self, n): return secrets.token_bytes(n)\n")
	_rs_sb(&buf, "    def urlsafe(self, n): return secrets.token_urlsafe(n)\n")
	_rs_sb(&buf, "    def digits(self, n): return ''.join(secrets.choice('0123456789') for _ in range(n))\n")
	_rs_sb(&buf, "    def hex(self, n): return secrets.token_hex(n)\n")
	_rs_sb(&buf, "\n")

	// Sign namespace
	_rs_sb(&buf, "class _SignNS:\n")
	_rs_sb(&buf, "    def hmac_sha256(self, key, message): return hmac.new(key, message, 'sha256').digest()\n")
	_rs_sb(&buf, "    def hmac_sha512(self, key, message): return hmac.new(key, message, 'sha512').digest()\n")
	_rs_sb(&buf, "    def ed25519(self, key, message):\n")
	_rs_sb(&buf, "        try:\n")
	_rs_sb(&buf, "            from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey\n")
	_rs_sb(&buf, "        except ImportError:\n")
	_rs_sb(&buf, "            raise ImportError(\n")
	_rs_sb(&buf, "                'mimir.crypt: Ed25519 requires the cryptography package. '\n")
	_rs_sb(&buf, "                'Install: pip install cryptography'\n")
	_rs_sb(&buf, "            )\n")
	_rs_sb(&buf, "        pk = Ed25519PrivateKey.from_private_bytes(key)\n")
	_rs_sb(&buf, "        return pk.sign(message)\n")
	_rs_sb(&buf, "\n")

	// Module wiring
	_rs_sb(&buf, "# Wire mimir.crypt module\n")
	_rs_sb(&buf, "_crypt_mod = ModuleType('mimir.crypt')\n")
	_rs_sb(&buf, "_crypt_mod.hash = _HashNS()\n")
	_rs_sb(&buf, "_crypt_mod.verify = _VerifyNS()\n")
	_rs_sb(&buf, "_crypt_mod.encrypt = _EncryptNS()\n")
	_rs_sb(&buf, "_crypt_mod.decrypt = _DecryptNS()\n")
	_rs_sb(&buf, "_crypt_mod.token = _TokenNS()\n")
	_rs_sb(&buf, "_crypt_mod.sign = _SignNS()\n")
	_rs_sb(&buf, "sys.modules['mimir.crypt'] = _crypt_mod\n")
	_rs_sb(&buf, "\n")

	return string(buf[:])
}

// ==================== mimir.json shim ====================

generate_json_shim :: proc(allocator: mem.Allocator) -> string {
	buf := make([dynamic]u8, 0, 1024, allocator)

	_rs_sb(&buf, "# ---- mimir.json runtime shim ----\n")
	_rs_sb(&buf, "import json as _json_stdlib\n")
	_rs_sb(&buf, "\n")
	_rs_sb(&buf, "def _json_parse(data, schema=None): return _json_stdlib.loads(data)\n")
	_rs_sb(&buf, "def _json_read(path, schema=None):\n")
	_rs_sb(&buf, "    with open(path, 'r') as f: return _json_stdlib.load(f)\n")
	_rs_sb(&buf, "def _json_serialize(obj): return _json_stdlib.dumps(obj)\n")
	_rs_sb(&buf, "def _json_write(obj, path):\n")
	_rs_sb(&buf, "    with open(path, 'w') as f: _json_stdlib.dump(obj, f)\n")
	_rs_sb(&buf, "def _json_load(path):\n")
	_rs_sb(&buf, "    with open(path, 'r') as f: return _json_stdlib.load(f)\n")
	_rs_sb(&buf, "def _json_loads(data): return _json_stdlib.loads(data)\n")
	_rs_sb(&buf, "def _json_dump(obj, path):\n")
	_rs_sb(&buf, "    with open(path, 'w') as f: _json_stdlib.dump(obj, f)\n")
	_rs_sb(&buf, "def _json_dumps(obj): return _json_stdlib.dumps(obj)\n")
	_rs_sb(&buf, "\n")

	// Module wiring
	_rs_sb(&buf, "# Wire mimir.json module\n")
	_rs_sb(&buf, "_json_mod = ModuleType('mimir.json')\n")
	_rs_sb(&buf, "_json_mod.parse = _json_parse\n")
	_rs_sb(&buf, "_json_mod.read = _json_read\n")
	_rs_sb(&buf, "_json_mod.serialize = _json_serialize\n")
	_rs_sb(&buf, "_json_mod.write = _json_write\n")
	_rs_sb(&buf, "_json_mod.load = _json_load\n")
	_rs_sb(&buf, "_json_mod.loads = _json_loads\n")
	_rs_sb(&buf, "_json_mod.dump = _json_dump\n")
	_rs_sb(&buf, "_json_mod.dumps = _json_dumps\n")
	_rs_sb(&buf, "sys.modules['mimir.json'] = _json_mod\n")
	_rs_sb(&buf, "\n")

	return string(buf[:])
}

// ==================== Utilities ====================

// Append string to byte buffer (byte-level, no rune truncation).
@(private = "file")
_rs_sb :: proc(buf: ^[dynamic]u8, s: string) {
	for i in 0..<len(s) { append(buf, s[i]) }
}

// Escape a string for embedding in Python single-quoted string literals.
@(private = "file")
_rs_escape_py_str :: proc(s: string) -> string {
	needs_escape := false
	for i in 0..<len(s) {
		c := s[i]
		if c == '\'' || c == '\\' || c == '\n' || c == '\r' || c == 0 {
			needs_escape = true
			break
		}
	}
	if !needs_escape { return s }

	result := make([dynamic]u8, 0, len(s) + 8, context.temp_allocator)
	for i in 0..<len(s) {
		c := s[i]
		switch c {
		case '\'':  append(&result, '\\'); append(&result, '\'')
		case '\\':  append(&result, '\\'); append(&result, '\\')
		case '\n':  append(&result, '\\'); append(&result, 'n')
		case '\r':  append(&result, '\\'); append(&result, 'r')
		case 0:     append(&result, '\\'); append(&result, '0')
		case:       append(&result, c)
		}
	}
	return string(result[:])
}
