package gpu

import "core:mem"
import "core:fmt"
import "core:strings"

import checker "mimir:checker"

// GPU Host Runtime — generates JS WebGPU dispatch code for emitted WGSL shaders.
// `mimir compile-gpu --host` produces: model.wgsl + model.js + model.d.ts

// Generate WebGPU host runtime JS for a compute graph.
emit_host_js :: proc(
	graph: ^Compute_Graph,
	bindings: ^Binding_Info,
	type_ctx: ^GPU_Type_Context,
	wgsl_filename: string,
	allocator: mem.Allocator,
) -> string {
	b := strings.builder_make(0, 4096, allocator)

	func_name := graph.func_name
	is_matmul := has_matmul(graph)

	fmt.sbprint(&b, "// Auto-generated by mimir compile-gpu --host\n")
	fmt.sbprint(&b, "// WebGPU dispatch runtime for WGSL compute shaders\n\n")

	// Loader function
	fmt.sbprintf(&b, "export async function load(device) {{\n")
	fmt.sbprint(&b, "  if (!device) {\n")
	fmt.sbprint(&b, "    const adapter = await navigator.gpu.requestAdapter();\n")
	fmt.sbprint(&b, "    if (!adapter) throw new Error('WebGPU not supported');\n")
	fmt.sbprint(&b, "    device = await adapter.requestDevice();\n")
	fmt.sbprint(&b, "  }\n\n")

	// Load shader
	fmt.sbprint(&b, "  let shaderCode;\n")
	fmt.sbprint(&b, "  if (typeof fetch === 'function') {\n")
	fmt.sbprintf(&b, "    const resp = await fetch('%s');\n", wgsl_filename)
	fmt.sbprint(&b, "    shaderCode = await resp.text();\n")
	fmt.sbprint(&b, "  } else {\n")
	fmt.sbprint(&b, "    const fs = await import('fs');\n")
	fmt.sbprintf(&b, "    shaderCode = fs.readFileSync('%s', 'utf-8');\n", wgsl_filename)
	fmt.sbprint(&b, "  }\n\n")

	// Create shader module
	fmt.sbprint(&b, "  const shaderModule = device.createShaderModule({ code: shaderCode });\n\n")

	// Create pipeline
	fmt.sbprintf(&b, "  const pipeline = device.createComputePipeline({{\n")
	fmt.sbprint(&b, "    layout: 'auto',\n")
	fmt.sbprint(&b, "    compute: {\n")
	fmt.sbprint(&b, "      module: shaderModule,\n")
	fmt.sbprintf(&b, "      entryPoint: 'kernel_%s',\n", func_name)
	fmt.sbprint(&b, "    },\n")
	fmt.sbprint(&b, "  });\n\n")

	// Build the dispatch function
	fmt.sbprintf(&b, "  return {{\n")
	fmt.sbprint(&b, "    device,\n")
	fmt.sbprint(&b, "    pipeline,\n\n")

	// Main dispatch method
	fmt.sbprintf(&b, "    async %s(", func_name)

	// Parameters
	first := true
	for inp in graph.inputs {
		node := _safe_node(graph, inp)
		if !first { fmt.sbprint(&b, ", ") }
		fmt.sbprintf(&b, "%s", node.name if len(node.name) > 0 else fmt.tprintf("input_%d", int(inp)))
		first = false
	}

	if is_matmul {
		if !first { fmt.sbprint(&b, ", ") }
		fmt.sbprint(&b, "dims")
	}

	fmt.sbprint(&b, ") {\n")

	// Create input buffers
	for inp in graph.inputs {
		node := _safe_node(graph, inp)
		binding := bindings.param_bindings[inp]
		param_name := node.name if len(node.name) > 0 else fmt.tprintf("input_%d", int(inp))

		fmt.sbprintf(&b, "      const buf_%s = device.createBuffer({{\n", param_name)
		fmt.sbprintf(&b, "        size: %s.byteLength,\n", param_name)
		fmt.sbprint(&b, "        usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST,\n")
		fmt.sbprint(&b, "      });\n")
		fmt.sbprintf(&b, "      device.queue.writeBuffer(buf_%s, 0, %s);\n\n", param_name, param_name)
	}

	// Create output buffers
	for out, out_idx in graph.outputs {
		node_idx := int(out)
		if node_idx >= len(graph.nodes) { node_idx = len(graph.nodes) - 1 }
		node := graph.nodes[node_idx]
		out_size := _compute_buffer_size(node, type_ctx)

		fmt.sbprintf(&b, "      const buf_output_%d = device.createBuffer({{\n", out_idx)
		fmt.sbprintf(&b, "        size: %d,\n", out_size)
		fmt.sbprint(&b, "        usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_SRC,\n")
		fmt.sbprint(&b, "      });\n\n")
	}

	// Uniform buffer for MatMul dimensions
	if is_matmul {
		fmt.sbprint(&b, "      const uniformBuffer = device.createBuffer({\n")
		fmt.sbprint(&b, "        size: 12, // 3 x u32: M, K, N\n")
		fmt.sbprint(&b, "        usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST,\n")
		fmt.sbprint(&b, "      });\n")
		fmt.sbprint(&b, "      device.queue.writeBuffer(uniformBuffer, 0, new Uint32Array([dims.M, dims.K, dims.N]));\n\n")
	}

	// Bind group entries
	fmt.sbprint(&b, "      const bindGroup = device.createBindGroup({\n")
	fmt.sbprint(&b, "        layout: pipeline.getBindGroupLayout(0),\n")
	fmt.sbprint(&b, "        entries: [\n")

	for inp in graph.inputs {
		node := _safe_node(graph, inp)
		binding := bindings.param_bindings[inp]
		param_name := node.name if len(node.name) > 0 else fmt.tprintf("input_%d", int(inp))
		fmt.sbprintf(&b, "          {{ binding: %d, resource: {{ buffer: buf_%s }} }},\n", binding, param_name)
	}

	for out, oi in graph.outputs {
		binding := bindings.output_bindings[out]
		fmt.sbprintf(&b, "          {{ binding: %d, resource: {{ buffer: buf_output_%d }} }},\n", binding, oi)
	}

	if is_matmul {
		fmt.sbprintf(&b, "          {{ binding: %d, resource: {{ buffer: uniformBuffer }} }},\n", bindings.total_bindings)
	}

	fmt.sbprint(&b, "        ],\n")
	fmt.sbprint(&b, "      });\n\n")

	// Dispatch
	fmt.sbprint(&b, "      const commandEncoder = device.createCommandEncoder();\n")
	fmt.sbprint(&b, "      const passEncoder = commandEncoder.beginComputePass();\n")
	fmt.sbprint(&b, "      passEncoder.setPipeline(pipeline);\n")
	fmt.sbprint(&b, "      passEncoder.setBindGroup(0, bindGroup);\n")

	if is_matmul {
		fmt.sbprint(&b, "      passEncoder.dispatchWorkgroups(Math.ceil(dims.N / 8), Math.ceil(dims.M / 8));\n")
	} else {
		// Compute dispatch size from first input shape
		fmt.sbprint(&b, "      const numElements = ")
		if len(graph.inputs) > 0 {
			node := _safe_node(graph, graph.inputs[0])
			param_name := node.name if len(node.name) > 0 else fmt.tprintf("input_%d", int(graph.inputs[0]))
			fmt.sbprintf(&b, "%s.length", param_name)
		} else {
			fmt.sbprint(&b, "1")
		}
		fmt.sbprint(&b, ";\n")
		fmt.sbprint(&b, "      passEncoder.dispatchWorkgroups(Math.ceil(numElements / 64));\n")
	}

	fmt.sbprint(&b, "      passEncoder.end();\n\n")

	// Read back results
	for out, oi in graph.outputs {
		out_size := _compute_buffer_size(_safe_node(graph, out), type_ctx)
		fmt.sbprintf(&b, "      const readBuffer_%d = device.createBuffer({{\n", oi)
		fmt.sbprintf(&b, "        size: %d,\n", out_size)
		fmt.sbprint(&b, "        usage: GPUBufferUsage.MAP_READ | GPUBufferUsage.COPY_DST,\n")
		fmt.sbprint(&b, "      });\n")
		fmt.sbprintf(&b, "      commandEncoder.copyBufferToBuffer(buf_output_%d, 0, readBuffer_%d, 0, %d);\n\n",
			oi, oi, out_size)
	}

	fmt.sbprint(&b, "      device.queue.submit([commandEncoder.finish()]);\n\n")

	// Map and return results
	if len(graph.outputs) == 1 {
		out := graph.outputs[0]
		elem_type := _js_typed_array(_safe_node(graph, out), type_ctx)
		fmt.sbprintf(&b, "      await readBuffer_0.mapAsync(GPUMapMode.READ);\n")
		fmt.sbprintf(&b, "      const result = new %s(readBuffer_0.getMappedRange().slice(0));\n", elem_type)
		fmt.sbprint(&b, "      readBuffer_0.unmap();\n")
		fmt.sbprint(&b, "      return result;\n")
	} else {
		fmt.sbprint(&b, "      const results = {};\n")
		for out, idx in graph.outputs {
			elem_type := _js_typed_array(_safe_node(graph, out), type_ctx)
			fmt.sbprintf(&b, "      await readBuffer_%d.mapAsync(GPUMapMode.READ);\n", idx)
			fmt.sbprintf(&b, "      results.output_%d = new %s(readBuffer_%d.getMappedRange().slice(0));\n", idx, elem_type, idx)
			fmt.sbprintf(&b, "      readBuffer_%d.unmap();\n", idx)
		}
		fmt.sbprint(&b, "      return results;\n")
	}

	fmt.sbprint(&b, "    },\n")
	fmt.sbprint(&b, "  };\n")
	fmt.sbprint(&b, "}\n")

	return strings.to_string(b)
}

// Generate TypeScript declarations for the GPU host runtime.
emit_host_ts :: proc(
	graph: ^Compute_Graph,
	type_ctx: ^GPU_Type_Context,
	allocator: mem.Allocator,
) -> string {
	b := strings.builder_make(0, 1024, allocator)

	func_name := graph.func_name
	is_matmul := has_matmul(graph)

	fmt.sbprint(&b, "// Auto-generated by mimir compile-gpu --host\n\n")

	fmt.sbprint(&b, "export interface GPURuntime {\n")
	fmt.sbprint(&b, "  device: GPUDevice;\n")
	fmt.sbprint(&b, "  pipeline: GPUComputePipeline;\n")

	// Dispatch method signature
	fmt.sbprintf(&b, "  %s(", func_name)
	first := true
	for inp in graph.inputs {
		node := _safe_node(graph, inp)
		if !first { fmt.sbprint(&b, ", ") }
		param_name := node.name if len(node.name) > 0 else fmt.tprintf("input_%d", int(inp))
		elem_type := _ts_typed_array(node, type_ctx)
		fmt.sbprintf(&b, "%s: %s", param_name, elem_type)
		first = false
	}
	if is_matmul {
		if !first { fmt.sbprint(&b, ", ") }
		fmt.sbprint(&b, "dims: { M: number; K: number; N: number }")
	}
	fmt.sbprint(&b, "): Promise<")

	if len(graph.outputs) == 1 {
		out := graph.outputs[0]
		fmt.sbprint(&b, _ts_typed_array(_safe_node(graph, out), type_ctx))
	} else {
		fmt.sbprint(&b, "Record<string, Float32Array | Int32Array>")
	}
	fmt.sbprint(&b, ">;\n")

	fmt.sbprint(&b, "}\n\n")
	fmt.sbprint(&b, "export function load(device?: GPUDevice): Promise<GPURuntime>;\n")

	return strings.to_string(b)
}

// ==================== Helpers ====================

_safe_node :: proc(graph: ^Compute_Graph, id: GPU_Node_ID) -> GPU_Node {
	idx := int(id)
	if idx >= len(graph.nodes) { idx = len(graph.nodes) - 1 }
	if idx < 0 { return {} }
	return graph.nodes[idx]
}

_compute_buffer_size :: proc(node: GPU_Node, type_ctx: ^GPU_Type_Context) -> int {
	elem_size := 4 // default f32
	if node.output_type == type_ctx.int32_id || node.output_type == checker.TYPE_INT {
		elem_size = 4
	} else if node.output_type == type_ctx.float16_id {
		elem_size = 2
	} else if node.output_type == type_ctx.int64_id {
		elem_size = 8
	}

	num_elements := 1
	if node.output_shape != nil {
		for dim in node.output_shape {
			num_elements *= dim
		}
	}

	size := num_elements * elem_size
	if size < 16 { size = 16 } // minimum buffer size
	return size
}

_js_typed_array :: proc(node: GPU_Node, type_ctx: ^GPU_Type_Context) -> string {
	if node.output_type == type_ctx.int32_id || node.output_type == checker.TYPE_INT {
		return "Int32Array"
	}
	if node.output_type == type_ctx.int64_id {
		return "BigInt64Array"
	}
	if node.output_type == type_ctx.float16_id {
		return "Float32Array" // f16 read back as f32
	}
	return "Float32Array"
}

_ts_typed_array :: proc(node: GPU_Node, type_ctx: ^GPU_Type_Context) -> string {
	if node.output_type == type_ctx.int32_id || node.output_type == checker.TYPE_INT {
		return "Int32Array"
	}
	if node.output_type == type_ctx.int64_id {
		return "BigInt64Array"
	}
	return "Float32Array"
}
